{{- $prefix := include "parasol-insurance-tenant.prefix" . -}}
{{- range $env := list "dev" "prod" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $prefix }}-{{ $env }}
  namespace: {{ $.Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $prefix }}-{{ $env }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.tenant.username }}
  source:
    path: app
    repoURL: https://{{ $.Values.gitlab.host }}/{{ $.Values.tenant.username }}/parasol-insurance-secured-manifests.git
    targetRevision: main
    helm:
      valueFiles:
        - values/values-{{ $env }}.yaml
      valuesObject:
        registry:
          host: {{ $.Values.registry.host }}
        cluster:
          subdomain: {{ $.Values.cluster.subdomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
