apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: trustify
  labels:
    {{- include "tpa-prerequisites.labels" . | nindent 4 }}
  annotations:
    {{- include "tpa-prerequisites.argocd-syncwave" . | nindent 4 }}
spec:
  bucketName: trustify
  storageClassName: openshift-storage.noobaa.io
