kind: Secret
apiVersion: v1
metadata:
  name: oidc-tpa-cli
  labels:
    {{- include "tpa-prerequisites.labels" . | nindent 4 }}
  annotations:
    {{- include "tpa-prerequisites.argocd-syncwave" . | nindent 4 }}
stringData:
  client-secret: {{ .Values.oidc.tpaCli.secret }}
type: Opaque
