{{- if not .Values.keycloak.disabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.keycloak.name "namespace" .Values.argocd.namespace "syncWave" "1") }}
spec:
  destination:
    namespace: {{ .Values.keycloak.namespace }}
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: KeycloakRealmImport
      jqPathExpressions:
        - .. | (.id, .containerId, .secret)? | strings
  source:
    path: keycloak
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        keycloak-operator:
          keycloak:
            subscription:
              source: {{ include "app-of-apps.operatorSource" . }}
        keycloak:
          nameOverride: {{ .Values.keycloak.crName }}
          route:
            host: {{ .Values.keycloak.route.host }}
          ingress:
            enabled: {{ .Values.keycloak.externalAccess }}
        keycloak-realm-import:
          keycloak:
            name: {{ .Values.keycloak.crName }}
          cluster:
            subdomain: {{ .Values.cluster.subdomain }}
          realm:
            name: {{ .Values.keycloak.realm.name }}
          client:
            backstage:
              name: {{ .Values.keycloak.client.backstage.name }}
              redirectUri: https://backstage-developer-hub-{{ .Values.developerHub.namespace }}.{{ .Values.cluster.subdomain }}/api/auth/oidc/handler/frame
              webOrigin: https://backstage-developer-hub-{{ .Values.developerHub.namespace }}.{{ .Values.cluster.subdomain }}
              secret: {{ .Values.keycloak.client.backstage.secret | quote }}
            backstagePlugin:
              name: {{ .Values.keycloak.client.backstagePlugin.name }}
              secret: {{ .Values.keycloak.client.backstagePlugin.secret | quote }}
            openshift:
              name: {{ .Values.keycloak.client.openshift.name }}
              redirectUri: {{ .Values.keycloak.client.openshift.redirectUri }}
              secret: {{ .Values.keycloak.client.openshift.secret | quote }}
            tpaFrontend:
              name: tpa-frontend
              redirectUri:
                - https://server-trusted-profile-analyzer.{{ .Values.cluster.subdomain }}
                - https://server-trusted-profile-analyzer.{{ .Values.cluster.subdomain }}/*
            tpaCli:
              name: tpa-cli
              secret: {{ .Values.keycloak.client.tpaCli.secret | quote }}
          users:
            password: {{ .Values.keycloak.users.password | quote }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
