apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.serviceMesh.name "namespace" .Values.argocd.namespace "syncWave" "0") }}
spec:
  destination:
    namespace: {{ .Values.serviceMesh.namespace }}
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: sailoperator.io
      kind: ZTunnel
      jsonPointers:
        - /spec/profile
  source:
    path: service-mesh
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        serviceMesh:
          source: {{ include "app-of-apps.operatorSource" . }}
        kiali:
          source: {{ include "app-of-apps.operatorSource" . }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m0s
      limit: 30
