site_name: OpenShift Advanced Application Platform Demo Lab
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Developer Experience: modules/module-01-developer-experience.md
  - Module 2 - Cicd Pipeline: modules/module-02-cicd-pipeline.md
  - Module 3 - Platform Operations: modules/module-03-platform-operations.md
  - Module 4 - Developer Hub: modules/module-04-developer-hub.md
  - Module 5 - Secure Development: modules/module-05-secure-development.md
  - Module 6 - Supply Chain: modules/module-06-supply-chain.md
  - Module 7 - Ai Applications: modules/module-07-ai-applications.md
plugins:
- techdocs-core
