tenant:
  username: ""

gitlab:
  host: ""

registry:
  host: ""

cluster:
  subdomain: ""

argocd:
  namespace: rhdh-gitops

vault:
  name: vault
  namespace: vault

database:
  image: registry.redhat.io/rhel8/postgresql-12:1
  user: parasol
  password: parasol
  name: parasol
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    capacity: 5Gi
