---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-plugins-root
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
