apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "create-ocp-namespace-swt.fullname" . }}-creds
  labels:
    {{- include "create-ocp-namespace-swt.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.vault.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "create-ocp-namespace-swt.fullname" . }}-creds
    creationPolicy: Owner
    template:
      data:
        BACKSTAGE_BACKEND_URL: {{ printf "https://backstage-developer-hub-rhdh.%s" .Values.cluster.subdomain | quote }}
        GITLAB_URL: {{ printf "https://gitlab-gitlab.%s" .Values.cluster.subdomain | quote }}
        SWT_REF: {{ .Values.env.swtRef | quote }}
        BACKSTAGE_BACKEND_BEARER_TOKEN: |-
          {{`{{ .backstageToken }}`}}
        GITLAB_TOKEN: |-
          {{`{{ .gitlabToken }}`}}
  data:
    - secretKey: backstageToken
      remoteRef:
        key: secrets/rhdh/orchestrator-token
        property: value
    - secretKey: gitlabToken
      remoteRef:
        key: secrets/gitlab/token
        property: value
