serverless:
  channel: stable
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

serverlessLogic:
  channel: stable
  installPlanApproval: Automatic
  name: logic-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
