apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - postgresql
    - database
  annotations:
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-label-selector: app=${{ values.name }}
spec:
  type: database
  owner: ${{ values.owner }}
  system: parasol-insurance
