#!/usr/bin/env bash
# Observability layer, step 3: Grafana fully configured (add-only).
#   - Grafana "grafana" in namespace observability (Grafana operator v5), edge route, persistent data,
#     admin password generated by the operator (secret grafana-admin-credentials), anonymous Viewer
#     access on (so links and embeds open without a second login) and embedding allowed.
#   - Datasources: Prometheus = OpenShift Thanos querier (service account grafana-thanos with
#     cluster-monitoring-view, token in secret grafana-thanos-token), Tempo = the tracing layer.
#   - Dashboards
#       folder "Istio":              Mesh, Workload, Service, Control Plane, Ztunnel (grafana.com)
#       folder "Connectivity Link":  Platform Engineer, App Developer, Business User (Kuadrant upstream)
#       folder "Parasol":            Parasol Platform Overview, Connectivity Link: Parasol API and LLM gateway (custom, build-dashboards.py)
#   - Kiali (both instances): Grafana links on workloads/services -> "Service Mesh" tab in Developer Hub shows them.
# Requires install-operators.sh (Grafana operator) and, for the Tempo datasource, tracing.sh.
set -euo pipefail
NS=observability
cd "$(dirname "$0")"
D=$(oc get ingresses.config cluster -o jsonpath='{.spec.domain}')
URL="https://grafana-route-${NS}.${D}"   # route name the operator creates: grafana-route

echo "== service account for Thanos"
oc get sa grafana-thanos -n $NS >/dev/null 2>&1 || oc create sa grafana-thanos -n $NS >/dev/null
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-thanos -n $NS >/dev/null
oc apply -f - <<Y >/dev/null
apiVersion: v1
kind: Secret
metadata:
  name: grafana-thanos-token
  namespace: ${NS}
  annotations:
    kubernetes.io/service-account.name: grafana-thanos
type: kubernetes.io/service-account-token
Y
for i in $(seq 1 20); do [ -n "$(oc get secret grafana-thanos-token -n $NS -o jsonpath='{.data.token}' 2>/dev/null)" ] && break; sleep 2; done
# the datasource needs "Bearer <token>" as a single secret value
TOKEN=$(oc get secret grafana-thanos-token -n $NS -o jsonpath='{.data.token}' | base64 -d)
oc create secret generic grafana-thanos-bearer -n $NS --from-literal=bearer="Bearer ${TOKEN}" --dry-run=client -o yaml | oc apply -f - >/dev/null

echo "== Grafana instance"
oc apply -f - <<Y
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: ${NS}
  labels:
    dashboards: parasol
spec:
  version: 11.3.0
  config:
    server:
      root_url: ${URL}
    auth.anonymous:
      enabled: "true"
      org_role: Viewer
    security:
      allow_embedding: "true"
      cookie_samesite: none
      cookie_secure: "true"
    users:
      viewers_can_edit: "false"
    analytics:
      reporting_enabled: "false"
      check_for_updates: "false"
    log:
      mode: console
  persistentVolumeClaim:
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 2Gi
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
          containers:
            - name: grafana
              volumeMounts:
                - name: grafana-data
                  mountPath: /var/lib/grafana
  route:
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
Y
for i in $(seq 1 30); do oc get deployment grafana-deployment -n $NS >/dev/null 2>&1 && break; sleep 5; done
oc rollout status deployment/grafana-deployment -n $NS --timeout=600s | tail -1

echo "== datasources"
oc apply -f - <<Y
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: ${NS}
spec:
  instanceSelector:
    matchLabels:
      dashboards: parasol
  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
          name: grafana-thanos-bearer
          key: bearer
  datasource:
    name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    jsonData:
      httpHeaderName1: Authorization
      tlsSkipVerify: true
      timeInterval: 30s
    secureJsonData:
      httpHeaderValue1: \${bearer}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: ${NS}
spec:
  instanceSelector:
    matchLabels:
      dashboards: parasol
  datasource:
    name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo-tempo.${NS}.svc:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
Y

apply_dashboards() {
echo "== dashboards: Istio (grafana.com)"
gcom() { # name folder id
  oc apply -f - <<Y >/dev/null
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: $1
  namespace: ${NS}
spec:
  instanceSelector:
    matchLabels:
      dashboards: parasol
  folder: "$2"
  resyncPeriod: 24h
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
  grafanaCom:
    id: $3
Y
}
gcom istio-mesh          Istio 7639
gcom istio-workload      Istio 7630
gcom istio-service       Istio 7636
gcom istio-control-plane Istio 7645
gcom istio-ztunnel       Istio 21306

echo "== dashboards: Connectivity Link (Kuadrant upstream)"
kd() { # name file
  oc apply -f - <<Y >/dev/null
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: $1
  namespace: ${NS}
spec:
  instanceSelector:
    matchLabels:
      dashboards: parasol
  folder: "Connectivity Link"
  resyncPeriod: 24h
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
  url: https://raw.githubusercontent.com/Kuadrant/kuadrant-operator/main/examples/dashboards/$2
Y
}
kd rhcl-platform-engineer platform_engineer.json
kd rhcl-app-developer     app_developer.json
kd rhcl-business-user     business_user.json

echo "== dashboards: Parasol (custom)"
python3 build-dashboards.py dashboards >/dev/null
for uid in parasol-overview parasol-rhcl; do
  oc create cm grafana-dash-$uid -n $NS --from-file=$uid.json=dashboards/$uid.json --dry-run=client -o yaml | oc apply -f - >/dev/null
  oc apply -f - <<Y >/dev/null
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: $uid
  namespace: ${NS}
spec:
  instanceSelector:
    matchLabels:
      dashboards: parasol
  folder: Parasol
  configMapRef:
    name: grafana-dash-$uid
    key: $uid.json
Y
done
}
apply_dashboards

echo "== Kiali: Grafana links (Service Mesh tab in Developer Hub shows them)"
GRAF='{"spec":{"external_services":{"grafana":{"enabled":true,"internal_url":"http://grafana-service.'"$NS"'.svc:3000","external_url":"'"$URL"'","auth":{"type":"none"},"dashboards":[{"name":"Istio Workload Dashboard","variables":{"namespace":"var-namespace","workload":"var-workload"}},{"name":"Istio Service Dashboard","variables":{"namespace":"var-namespace","service":"var-service"}},{"name":"Istio Mesh Dashboard"},{"name":"Parasol Platform Overview","variables":{"namespace":"var-namespace"}}]}}}}'
oc patch kiali kiali -n istio-system --type merge -p "$GRAF" >/dev/null
oc patch kiali kiali-rhdh -n istio-system --type merge -p "$GRAF" >/dev/null 2>&1 || true

echo "== check (the operator provisions datasources and dashboards; a fresh instance needs one operator pass)"
ADM="$(oc get secret grafana-admin-credentials -n $NS -o jsonpath='{.data.GF_SECURITY_ADMIN_USER}' | base64 -d):$(oc get secret grafana-admin-credentials -n $NS -o jsonpath='{.data.GF_SECURITY_ADMIN_PASSWORD}' | base64 -d)"
for i in $(seq 1 12); do
  nds=$(curl -sk -u "$ADM" "$URL/api/datasources" | jq 'length' 2>/dev/null || echo 0)
  ndb=$(curl -sk -u "$ADM" "$URL/api/search?type=dash-db" | jq 'length' 2>/dev/null || echo 0)
  [ "${nds:-0}" -ge 2 ] && [ "${ndb:-0}" -ge 10 ] && break
  [ "$i" = 3 ] && { echo "   nudging the operator to re-provision"; oc rollout restart deployment/grafana-operator-controller-manager-v5 -n $NS >/dev/null; }
  # the operator remembers dashboards as applied even when the instance was recreated: recreate the CRs
  [ "$i" = 7 ] && { echo "   recreating the dashboard resources"; oc delete grafanadashboard --all -n $NS >/dev/null; apply_dashboards >/dev/null; }
  sleep 15
done
curl -sk -o /dev/null -w "   grafana route: %{http_code}\n" "$URL/api/health"
echo "   datasources: $(curl -sk -u "$ADM" "$URL/api/datasources" | jq -r '.[].name' | tr '\n' ' ')"
echo "   dashboards ($ndb): $(curl -sk -u "$ADM" "$URL/api/search?type=dash-db" | jq -r '.[] | "\(.folderTitle // "-")/\(.title)"' | sort | tr '\n' ';' | head -c 700)"
echo "Done. Grafana: $URL (admin password: oc get secret grafana-admin-credentials -n $NS -o jsonpath='{.data.GF_SECURITY_ADMIN_PASSWORD}' | base64 -d)"
